# match:content[int] | game is 3
windowrule {
    name="Elden Ring"
    match:title = Elden Ring
    match:fullscreen = true
    workspace = 3
    match:content = 3
}

windowrule {
  name="Elder Scrolls Online"
  match:title = Elder Scrolls Online
  match:fullscreen = false
  match:float = false
  workspace = 3
}
