# match:content[int] | game is 3
windowrule {
    name="Elden Ring"
    match:title = Elden Ring
    match:fullscreen = true
    match:workspace = 2
    match:content = 3
}

windowrule {
    name="gamescope"
    maximize = on
    match:class = gamescope
    match:content = 3
    match:workspace = 2
}

