###################
### LAYER RULES ###
###################
layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 0.5
  blur = true
  blur_popups = true
}
layerrule = match:namespace noctalia-shell:regionSelector, no_anim on

####################
### WINDOW RULES ###
####################
windowrule = match:class steam, match:workspace game
windowrule = match:class vesktop, match:workspace alt
windowrule = match:class jetbrains-rider, match:workspace dev

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Float
windowrule = match:float true, match:class ^(org.pulseaudio.pavucontrol)
windowrule = match:float true, match:class ^()$, match:title ^(Picture in picture)$
windowrule = match:float true, match:class ^()$, match:title ^(Save File)$
windowrule = match:float true, match:class ^()$, match:title ^(Open File)$
windowrule = match:float true, match:class ^(LibreWolf)$, match:title ^(Picture-in-Picture)$
windowrule = match:float true, match:class ^(blueman-manager)$
windowrule = match:float true, match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrule = match:float true, match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
windowrule = match:float true, match:class ^(CachyOSHello)$
windowrule = match:float true, match:class ^(zenity)$
windowrule = match:float true, match:class ^()$, match:title ^(Steam - Self Updater)$
windowrule = match:float true, match:class steam, match:title Friends List

windowrule = match:float true, match:class ^(jetbrains-toolbox)$

#######################
### WORKSPACE RULES ###
#######################
# Workspaces Rules https://wiki.hyprland.org/Configuring/Workspace-Rules/ #
# Workspace selectors https://wiki.hyprland.org/Configuring/Workspace-Rules/#workspace-selectors

workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]

workspace = 1, defaultName:main, monitor:$priMon, default:true, persistent:true
workspace = 2, defaultName:steam, monitor:$priMon, persistent:true
workspace = 3, f[1], gapsout:0, gapsin:0, defaultName:game, monitor:$priMon, persistent:true
workspace = 4, defaultName:dev, monitor:$priMon, persistent:true

workspace = 6, defaultName:alt, monitor:$secMon, default:true, persistent:true, layoutopt:orientation:top
