require("config.monitors")
require("config.config")
require("config.rules")
require("config.game_rules")
require("config.animations")
require("noctalia/noctalia-colors")

require("config.binds")
require("config.startup")
require("games.osu")
