-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        snap = {
            enabled = true,
        },
    },
})

-- Monitors
hl.monitor({
    output = "DP-1",
    disabled = false,
    mode = "5120x1440@240.00Hz",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    vrr = 0,
    cm = "wide",
})
